// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZevr4Y3hYysro024YIwAtWCXBF7gytnU',
    appId: '1:1049141497841:web:4a1b30bf42f34231777e50',
    messagingSenderId: '1049141497841',
    projectId: 'student-info-8faf4',
    authDomain: 'student-info-8faf4.firebaseapp.com',
    storageBucket: 'student-info-8faf4.firebasestorage.app',
    measurementId: 'G-YGF2ZFK2LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkm-m9Z7yeUQQC4bHE5rVX9y2CpXzPD-4',
    appId: '1:1049141497841:android:e8028e5711609d0b777e50',
    messagingSenderId: '1049141497841',
    projectId: 'student-info-8faf4',
    storageBucket: 'student-info-8faf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM2j9114NB1BScBiDXLfrso-22IOCAdO4',
    appId: '1:1049141497841:ios:d21ec4d08a757eaf777e50',
    messagingSenderId: '1049141497841',
    projectId: 'student-info-8faf4',
    storageBucket: 'student-info-8faf4.firebasestorage.app',
    iosBundleId: 'com.example.projectFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM2j9114NB1BScBiDXLfrso-22IOCAdO4',
    appId: '1:1049141497841:ios:d21ec4d08a757eaf777e50',
    messagingSenderId: '1049141497841',
    projectId: 'student-info-8faf4',
    storageBucket: 'student-info-8faf4.firebasestorage.app',
    iosBundleId: 'com.example.projectFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZevr4Y3hYysro024YIwAtWCXBF7gytnU',
    appId: '1:1049141497841:web:9d5cb6da8973f71f777e50',
    messagingSenderId: '1049141497841',
    projectId: 'student-info-8faf4',
    authDomain: 'student-info-8faf4.firebaseapp.com',
    storageBucket: 'student-info-8faf4.firebasestorage.app',
    measurementId: 'G-NYFHYV4PCQ',
  );

}