// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaBPoFKEB9csEgYwtFC7vKKisjWHylIZE',
    appId: '1:22063460733:web:24b5fc78308babcda19c14',
    messagingSenderId: '22063460733',
    projectId: 'batch-13-595e2',
    authDomain: 'batch-13-595e2.firebaseapp.com',
    storageBucket: 'batch-13-595e2.firebasestorage.app',
    measurementId: 'G-R71Q9Q12D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClSV5rFNnHwpo0MVOzOhIAHA0WoGE8XV8',
    appId: '1:22063460733:android:ffda28200e13d84ca19c14',
    messagingSenderId: '22063460733',
    projectId: 'batch-13-595e2',
    storageBucket: 'batch-13-595e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADtfSISaUuNH5CSYTa0bX3TjFKI1vfVpA',
    appId: '1:22063460733:ios:2dcff1a88e68f05fa19c14',
    messagingSenderId: '22063460733',
    projectId: 'batch-13-595e2',
    storageBucket: 'batch-13-595e2.firebasestorage.app',
    iosBundleId: 'com.example.projectFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADtfSISaUuNH5CSYTa0bX3TjFKI1vfVpA',
    appId: '1:22063460733:ios:2dcff1a88e68f05fa19c14',
    messagingSenderId: '22063460733',
    projectId: 'batch-13-595e2',
    storageBucket: 'batch-13-595e2.firebasestorage.app',
    iosBundleId: 'com.example.projectFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaBPoFKEB9csEgYwtFC7vKKisjWHylIZE',
    appId: '1:22063460733:web:63471f84fa85371ca19c14',
    messagingSenderId: '22063460733',
    projectId: 'batch-13-595e2',
    authDomain: 'batch-13-595e2.firebaseapp.com',
    storageBucket: 'batch-13-595e2.firebasestorage.app',
    measurementId: 'G-WF5FM5HFEM',
  );
}
